<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HBRB43M" failures="1" tests="5" name="Test" time="16.752" errors="0" timestamp="2023-08-05T11:29:19 IST">
  <testcase classname="mytestpackage.test.ValidationErrorTest" name="errorMessage" time="0.416">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect email or passwor.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or passwor.]
at mytestpackage.test.ValidationErrorTest.errorMessage(ValidationErrorTest.java:17)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- errorMessage -->
  <testcase classname="mytestpackage.test.StandAlone" name="submitOrder" time="4.428"/>
  <testcase classname="mytestpackage.test.StandAlone" name="submitOrder" time="4.309"/>
  <testcase classname="mytestpackage.test.StandAlone" name="verifyProduct" time="0.48"/>
  <testcase classname="mytestpackage.test.StandAlone" name="verifyProduct" time="0.537"/>
</testsuite> <!-- Test -->
